;
; File generated by cc65 v 2.18 - Git 5269552
;
	.fopt		compiler,"cc65 v 2.18 - Git 5269552"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_NMI_flag
	.export		_Frame_Count
	.export		_index
	.export		_index4
	.export		_state
	.export		_state4
	.export		_joypad1
	.export		_joypad1old
	.export		_joypad1test
	.export		_joypad2
	.export		_joypad2old
	.export		_joypad2test
	.export		_SPRITES
	.export		_PALETTE
	.export		_All_Off
	.export		_All_On
	.export		_Reset_Scroll
	.export		_Load_Palette
	.export		_move_logic
	.export		_play_level
	.export		_show_level_and_goal
	.export		_show_text
	.import		_Get_Input
	.export		_left
	.export		_right
	.export		_to_move
	.export		_MAX_LEFT
	.export		_MAX_RIGHT
	.export		_TO_WIN
	.export		_LEVEL_NUMBER
	.export		_WIN_LEVEL_TEXT
	.export		_LEVEL_NUMBER_TEXT
	.export		_GOAL_TEXT
	.export		_int_to_char
	.export		_show_win_level
	.export		_main

.segment	"DATA"

_left:
	.byte	$00
_right:
	.byte	$00
_to_move:
	.byte	$00

.segment	"RODATA"

_PALETTE:
	.byte	$1F
	.byte	$00
	.byte	$10
	.byte	$20
_MAX_LEFT:
	.byte	$05
_MAX_RIGHT:
	.byte	$03
_TO_WIN:
	.byte	$04
_LEVEL_NUMBER:
	.byte	$01
_WIN_LEVEL_TEXT:
	.byte	$4C,$45,$56,$45,$4C,$20,$50,$41,$53,$53,$45,$44,$21,$00
_LEVEL_NUMBER_TEXT:
	.byte	$4C,$45,$56,$45,$4C,$3A,$00
_GOAL_TEXT:
	.byte	$47,$4F,$41,$4C,$3A,$00

.segment	"BSS"

.segment	"ZEROPAGE"
_NMI_flag:
	.res	1,$00
_Frame_Count:
	.res	1,$00
_index:
	.res	1,$00
_index4:
	.res	1,$00
_state:
	.res	1,$00
_state4:
	.res	1,$00
_joypad1:
	.res	1,$00
_joypad1old:
	.res	1,$00
_joypad1test:
	.res	1,$00
_joypad2:
	.res	1,$00
_joypad2old:
	.res	1,$00
_joypad2test:
	.res	1,$00
.segment	"OAM"
_SPRITES:
	.res	256,$00

; ---------------------------------------------------------------
; void __near__ All_Off (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_All_Off: near

.segment	"CODE"

;
; PPU_CTRL = 0;
;
	lda     #$00
	sta     $2000
;
; PPU_MASK = 0; 
;
	sta     $2001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ All_On (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_All_On: near

.segment	"CODE"

;
; PPU_CTRL = 0x90; // screen is on, NMI on
;
	lda     #$90
	sta     $2000
;
; PPU_MASK = 0x1e; 
;
	lda     #$1E
	sta     $2001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Reset_Scroll (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Reset_Scroll: near

.segment	"CODE"

;
; PPU_ADDRESS = 0;
;
	lda     #$00
	sta     $2006
;
; PPU_ADDRESS = 0;
;
	sta     $2006
;
; SCROLL = 0;
;
	sta     $2005
;
; SCROLL = 0;
;
	sta     $2005
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Load_Palette (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Load_Palette: near

.segment	"CODE"

;
; PPU_ADDRESS = 0x3f;
;
	lda     #$3F
	sta     $2006
;
; PPU_ADDRESS = 0x00;
;
	lda     #$00
	sta     $2006
;
; for( index = 0; index < sizeof(PALETTE); ++index ){
;
	sta     _index
L011D:	lda     _index
	cmp     #$04
	bcs     L00CD
;
; PPU_DATA = PALETTE[index];
;
	ldy     _index
	lda     _PALETTE,y
	sta     $2007
;
; for( index = 0; index < sizeof(PALETTE); ++index ){
;
	inc     _index
	jmp     L011D
;
; }
;
L00CD:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ move_logic (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_move_logic: near

.segment	"CODE"

;
; void move_logic (unsigned char left_volume, unsigned char right_volume) {
;
	jsr     pusha
;
; if ((joypad1 & RIGHT) != 0){
;
	lda     _joypad1
	and     #$01
	beq     L011F
;
; to_move = right_volume - right;
;
	ldy     #$00
	lda     (sp),y
	sec
	sbc     _right
	sta     _to_move
;
; if (left > to_move){
;
	lda     _left
	sec
	sbc     _to_move
	bcc     L011E
	beq     L011E
;
; left -= to_move;
;
	lda     _to_move
	eor     #$FF
	sec
	adc     _left
	sta     _left
;
; right += to_move;
;
	lda     _to_move
	clc
	adc     _right
	sta     _right
;
; } else {
;
	jmp     L011F
;
; right += left;
;
L011E:	lda     _left
	clc
	adc     _right
	sta     _right
;
; left = 0;
;
	sty     _left
;
; if ((joypad1 & LEFT) != 0){
;
L011F:	lda     _joypad1
	and     #$02
	beq     L0121
;
; to_move = left_volume - left;
;
	ldy     #$01
	lda     (sp),y
	sec
	sbc     _left
	sta     _to_move
;
; if (right > to_move){
;
	lda     _right
	sec
	sbc     _to_move
	bcc     L0120
	beq     L0120
;
; right -= to_move;
;
	lda     _to_move
	eor     #$FF
	sec
	adc     _right
	sta     _right
;
; left += to_move;
;
	lda     _to_move
	clc
	adc     _left
	sta     _left
;
; } else {
;
	jmp     L0121
;
; left += right;
;
L0120:	lda     _right
	clc
	adc     _left
	sta     _left
;
; right = 0;
;
	lda     #$00
	sta     _right
;
; if ((joypad1 & B_BUTTON) != 0){
;
L0121:	lda     _joypad1
	and     #$40
	beq     L0123
;
; if ((joypad1 & DOWN) != 0){
;
	lda     _joypad1
	and     #$04
	beq     L0122
;
; left = left_volume;
;
	ldy     #$01
	lda     (sp),y
	sta     _left
;
; if ((joypad1 & UP) != 0){
;
L0122:	lda     _joypad1
	and     #$08
	beq     L0123
;
; left = 0;
;
	lda     #$00
	sta     _left
;
; if ((joypad1 & A_BUTTON) != 0){
;
L0123:	lda     _joypad1
	and     #$80
	beq     L0117
;
; if ((joypad1 & DOWN) != 0){
;
	lda     _joypad1
	and     #$04
	beq     L0124
;
; right = right_volume;
;
	ldy     #$00
	lda     (sp),y
	sta     _right
;
; if ((joypad1 & UP) != 0){
;
L0124:	lda     _joypad1
	and     #$08
	beq     L0117
;
; right = 0;
;
	lda     #$00
	sta     _right
;
; }
;
L0117:	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ play_level (unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_play_level: near

.segment	"CODE"

;
; void play_level(unsigned char level_number, unsigned char left_volume, unsigned char right_volume, unsigned char  goal){
;
	jsr     pusha
;
; Get_Input();
;
	jsr     _Get_Input
;
; move_logic(left_volume, right_volume);
;
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _move_logic
;
; show_text(level_number, goal);
;
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _show_text
;
; if ((left == goal)||(right == goal)){
;
	ldy     #$00
	lda     (sp),y
	cmp     _left
	beq     L0127
	cmp     _right
	jne     incsp4
;
; show_win_level();
;
L0127:	jsr     _show_win_level
;
; }
;
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ show_level_and_goal (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_show_level_and_goal: near

.segment	"CODE"

;
; void show_level_and_goal (unsigned char level_number, unsigned char goal){
;
	jsr     pusha
;
; PPU_ADDRESS = 0x21;   // set an address in the PPU of 0x21ca
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0x01;   // left up corner
;
	lda     #$01
	sta     $2006
;
; for( index = 0; index < sizeof(LEVEL_NUMBER_TEXT); ++index ){
;
	lda     #$00
	sta     _index
L0128:	lda     _index
	cmp     #$07
	bcs     L0129
;
; PPU_DATA = LEVEL_NUMBER_TEXT[index];
;
	ldy     _index
	lda     _LEVEL_NUMBER_TEXT,y
	sta     $2007
;
; for( index = 0; index < sizeof(LEVEL_NUMBER_TEXT); ++index ){
;
	inc     _index
	jmp     L0128
;
; PPU_ADDRESS = 0x21;   // set an address in the PPU of 0x21ca
;
L0129:	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0x07;   // left up corner
;
	lda     #$07
	sta     $2006
;
; PPU_DATA = int_to_char(level_number); 
;
	ldy     #$01
	lda     (sp),y
	jsr     _int_to_char
	sta     $2007
;
; PPU_ADDRESS = 0x21;   // set an address in the PPU of 0x21ca
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0x19;   // right up corner
;
	lda     #$19
	sta     $2006
;
; for( index = 0; index < sizeof(GOAL_TEXT); ++index ){
;
	lda     #$00
	sta     _index
L012A:	lda     _index
	cmp     #$06
	bcs     L012B
;
; PPU_DATA = GOAL_TEXT[index];
;
	ldy     _index
	lda     _GOAL_TEXT,y
	sta     $2007
;
; for( index = 0; index < sizeof(GOAL_TEXT); ++index ){
;
	inc     _index
	jmp     L012A
;
; PPU_ADDRESS = 0x21;   // set an address in the PPU of 0x21ca
;
L012B:	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0x1e;   // right up corner
;
	lda     #$1E
	sta     $2006
;
; PPU_DATA = int_to_char(goal); 
;
	ldy     #$00
	lda     (sp),y
	jsr     _int_to_char
	sta     $2007
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ show_text (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_show_text: near

.segment	"CODE"

;
; void show_text(unsigned char level_number, unsigned char goal) {
;
	jsr     pusha
;
; All_Off();
;
	jsr     _All_Off
;
; Load_Palette();
;
	jsr     _Load_Palette
;
; PPU_ADDRESS = 0x21;   // set an address in the PPU of 0x21ca
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0x6b;   // about the middle of the screen
;
	lda     #$6B
	sta     $2006
;
; PPU_DATA = int_to_char(left);
;
	lda     _left
	jsr     _int_to_char
	sta     $2007
;
; PPU_ADDRESS = 0x21;   // set an address in the PPU of 0x21ca
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0x73;   // about the middle of the screen
;
	lda     #$73
	sta     $2006
;
; PPU_DATA = int_to_char(right); 
;
	lda     _right
	jsr     _int_to_char
	sta     $2007
;
; if (level_number > 0) {
;
	ldy     #$01
	lda     (sp),y
	beq     L002C
;
; show_level_and_goal(level_number, goal);
;
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _show_level_and_goal
;
; Reset_Scroll();
;
L002C:	jsr     _Reset_Scroll
;
; All_On();
;
	jsr     _All_On
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ int_to_char (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_int_to_char: near

.segment	"CODE"

;
; char int_to_char(char i) {
;
	jsr     pusha
;
; return i + '0';
;
	ldy     #$00
	lda     (sp),y
	clc
	adc     #$30
	ldx     #$00
;
; } 
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ show_win_level (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_show_win_level: near

.segment	"CODE"

;
; All_Off();
;
	jsr     _All_Off
;
; Load_Palette();
;
	jsr     _Load_Palette
;
; PPU_ADDRESS = 0x21;   // set an address in the PPU of 0x21ca
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0xc9;   // about the middle of the screen
;
	lda     #$C9
	sta     $2006
;
; for( index = 0; index < sizeof(WIN_LEVEL_TEXT); ++index ){
;
	lda     #$00
	sta     _index
L012C:	lda     _index
	cmp     #$0E
	bcs     L007A
;
; PPU_DATA = WIN_LEVEL_TEXT[index];
;
	ldy     _index
	lda     _WIN_LEVEL_TEXT,y
	sta     $2007
;
; for( index = 0; index < sizeof(WIN_LEVEL_TEXT); ++index ){
;
	inc     _index
	jmp     L012C
;
; Reset_Scroll();
;
L007A:	jsr     _Reset_Scroll
;
; All_On();
;
	jmp     _All_On

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; show_text(0, 0);
;
	lda     #$00
	jsr     pusha
	jsr     _show_text
;
; while (NMI_flag == 0); // wait till NMI
;
L012D:	lda     _NMI_flag
	beq     L012D
;
; play_level(LEVEL_NUMBER, MAX_LEFT, MAX_RIGHT, TO_WIN);
;
	jsr     decsp3
	lda     _LEVEL_NUMBER
	ldy     #$02
	sta     (sp),y
	lda     _MAX_LEFT
	dey
	sta     (sp),y
	lda     _MAX_RIGHT
	dey
	sta     (sp),y
	lda     _TO_WIN
	jsr     _play_level
;
; NMI_flag = 0;
;
	lda     #$00
	sta     _NMI_flag
;
; while (1){   // infinite loop
;
	jmp     L012D

.endproc

