;
; File generated by cc65 v 2.18 - Git 5269552
;
	.fopt		compiler,"cc65 v 2.18 - Git 5269552"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_NMI_flag
	.export		_Frame_Count
	.export		_index
	.export		_index4
	.export		_state
	.export		_state4
	.export		_joypad1
	.export		_joypad1old
	.export		_joypad1test
	.export		_joypad2
	.export		_joypad2old
	.export		_joypad2test
	.export		_SPRITES
	.export		_PALETTE
	.export		_All_Off
	.export		_All_On
	.export		_Reset_Scroll
	.export		_Load_Palette
	.export		_move_logic
	.import		_Get_Input
	.export		_left
	.export		_right
	.export		_to_move
	.export		_MAX_LEFT
	.export		_MAX_RIGHT
	.export		_TO_WIN
	.export		_WIN_TEXT
	.export		_int_to_char
	.export		_show_text
	.export		_show_win
	.export		_main

.segment	"DATA"

_left:
	.byte	$00
_right:
	.byte	$00
_to_move:
	.byte	$00

.segment	"RODATA"

_PALETTE:
	.byte	$1F
	.byte	$00
	.byte	$10
	.byte	$20
_MAX_LEFT:
	.byte	$05
_MAX_RIGHT:
	.byte	$03
_TO_WIN:
	.byte	$04
_WIN_TEXT:
	.byte	$59,$4F,$55,$20,$57,$4F,$4E,$21,$00

.segment	"BSS"

.segment	"ZEROPAGE"
_NMI_flag:
	.res	1,$00
_Frame_Count:
	.res	1,$00
_index:
	.res	1,$00
_index4:
	.res	1,$00
_state:
	.res	1,$00
_state4:
	.res	1,$00
_joypad1:
	.res	1,$00
_joypad1old:
	.res	1,$00
_joypad1test:
	.res	1,$00
_joypad2:
	.res	1,$00
_joypad2old:
	.res	1,$00
_joypad2test:
	.res	1,$00
.segment	"OAM"
_SPRITES:
	.res	256,$00

; ---------------------------------------------------------------
; void __near__ All_Off (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_All_Off: near

.segment	"CODE"

;
; PPU_CTRL = 0;
;
	lda     #$00
	sta     $2000
;
; PPU_MASK = 0; 
;
	sta     $2001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ All_On (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_All_On: near

.segment	"CODE"

;
; PPU_CTRL = 0x90; // screen is on, NMI on
;
	lda     #$90
	sta     $2000
;
; PPU_MASK = 0x1e; 
;
	lda     #$1E
	sta     $2001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Reset_Scroll (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Reset_Scroll: near

.segment	"CODE"

;
; PPU_ADDRESS = 0;
;
	lda     #$00
	sta     $2006
;
; PPU_ADDRESS = 0;
;
	sta     $2006
;
; SCROLL = 0;
;
	sta     $2005
;
; SCROLL = 0;
;
	sta     $2005
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Load_Palette (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Load_Palette: near

.segment	"CODE"

;
; PPU_ADDRESS = 0x3f;
;
	lda     #$3F
	sta     $2006
;
; PPU_ADDRESS = 0x00;
;
	lda     #$00
	sta     $2006
;
; for( index = 0; index < sizeof(PALETTE); ++index ){
;
	sta     _index
L00CC:	lda     _index
	cmp     #$04
	bcs     L007C
;
; PPU_DATA = PALETTE[index];
;
	ldy     _index
	lda     _PALETTE,y
	sta     $2007
;
; for( index = 0; index < sizeof(PALETTE); ++index ){
;
	inc     _index
	jmp     L00CC
;
; }
;
L007C:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ move_logic (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_move_logic: near

.segment	"CODE"

;
; if ((joypad1 & RIGHT) != 0){
;
	lda     _joypad1
	and     #$01
	beq     L00CE
;
; to_move = MAX_RIGHT - right;
;
	lda     _MAX_RIGHT
	sec
	sbc     _right
	sta     _to_move
;
; if (left > to_move){
;
	lda     _left
	sec
	sbc     _to_move
	bcc     L00CD
	beq     L00CD
;
; left -= to_move;
;
	lda     _to_move
	eor     #$FF
	sec
	adc     _left
	sta     _left
;
; right += to_move;
;
	lda     _to_move
	clc
	adc     _right
	sta     _right
;
; } else {
;
	jmp     L00CE
;
; right += left;
;
L00CD:	lda     _left
	clc
	adc     _right
	sta     _right
;
; left = 0;
;
	lda     #$00
	sta     _left
;
; if ((joypad1 & LEFT) != 0){
;
L00CE:	lda     _joypad1
	and     #$02
	beq     L00D0
;
; to_move = MAX_LEFT - left;
;
	lda     _MAX_LEFT
	sec
	sbc     _left
	sta     _to_move
;
; if (right > to_move){
;
	lda     _right
	sec
	sbc     _to_move
	bcc     L00CF
	beq     L00CF
;
; right -= to_move;
;
	lda     _to_move
	eor     #$FF
	sec
	adc     _right
	sta     _right
;
; left += to_move;
;
	lda     _to_move
	clc
	adc     _left
	sta     _left
;
; } else {
;
	jmp     L00D0
;
; left += right;
;
L00CF:	lda     _right
	clc
	adc     _left
	sta     _left
;
; right = 0;
;
	lda     #$00
	sta     _right
;
; if ((joypad1 & B_BUTTON) != 0){
;
L00D0:	lda     _joypad1
	and     #$40
	beq     L00D2
;
; if ((joypad1 & DOWN) != 0){
;
	lda     _joypad1
	and     #$04
	beq     L00D1
;
; left = MAX_LEFT;
;
	lda     _MAX_LEFT
	sta     _left
;
; if ((joypad1 & UP) != 0){
;
L00D1:	lda     _joypad1
	and     #$08
	beq     L00D2
;
; left = 0;
;
	lda     #$00
	sta     _left
;
; if ((joypad1 & A_BUTTON) != 0){
;
L00D2:	lda     _joypad1
	and     #$80
	beq     L00C6
;
; if ((joypad1 & DOWN) != 0){
;
	lda     _joypad1
	and     #$04
	beq     L00D3
;
; right = MAX_RIGHT;
;
	lda     _MAX_RIGHT
	sta     _right
;
; if ((joypad1 & UP) != 0){
;
L00D3:	lda     _joypad1
	and     #$08
	beq     L00C6
;
; right = 0;
;
	lda     #$00
	sta     _right
;
; }
;
L00C6:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ int_to_char (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_int_to_char: near

.segment	"CODE"

;
; char int_to_char(char i) {
;
	jsr     pusha
;
; return i + '0';
;
	ldy     #$00
	lda     (sp),y
	clc
	adc     #$30
	ldx     #$00
;
; } 
;
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ show_text (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_show_text: near

.segment	"CODE"

;
; All_Off();
;
	jsr     _All_Off
;
; Load_Palette();
;
	jsr     _Load_Palette
;
; PPU_ADDRESS = 0x21;   // set an address in the PPU of 0x21ca
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0x4b;   // about the middle of the screen
;
	lda     #$4B
	sta     $2006
;
; PPU_DATA = int_to_char(left);
;
	lda     _left
	jsr     _int_to_char
	sta     $2007
;
; PPU_ADDRESS = 0x21;   // set an address in the PPU of 0x21ca
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0x54;   // about the middle of the screen
;
	lda     #$54
	sta     $2006
;
; PPU_DATA = int_to_char(right); 
;
	lda     _right
	jsr     _int_to_char
	sta     $2007
;
; Reset_Scroll();
;
	jsr     _Reset_Scroll
;
; All_On();
;
	jmp     _All_On

.endproc

; ---------------------------------------------------------------
; void __near__ show_win (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_show_win: near

.segment	"CODE"

;
; All_Off();
;
	jsr     _All_Off
;
; Load_Palette();
;
	jsr     _Load_Palette
;
; PPU_ADDRESS = 0x21;   // set an address in the PPU of 0x21ca
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0xcc;   // about the middle of the screen
;
	lda     #$CC
	sta     $2006
;
; for( index = 0; index < sizeof(WIN_TEXT); ++index ){
;
	lda     #$00
	sta     _index
L00D4:	lda     _index
	cmp     #$09
	bcs     L0035
;
; PPU_DATA = WIN_TEXT[index];
;
	ldy     _index
	lda     _WIN_TEXT,y
	sta     $2007
;
; for( index = 0; index < sizeof(WIN_TEXT); ++index ){
;
	inc     _index
	jmp     L00D4
;
; Reset_Scroll();
;
L0035:	jsr     _Reset_Scroll
;
; All_On();
;
	jmp     _All_On

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; show_text();
;
	jsr     _show_text
;
; while (NMI_flag == 0); // wait till NMI
;
L00D7:	lda     _NMI_flag
	beq     L00D7
;
; Get_Input();
;
	jsr     _Get_Input
;
; move_logic();
;
	jsr     _move_logic
;
; show_text();
;
	jsr     _show_text
;
; if ((left == TO_WIN)||(right == TO_WIN)){
;
	lda     _TO_WIN
	cmp     _left
	beq     L00D8
	cmp     _right
	bne     L00DB
;
; show_win();
;
L00D8:	jsr     _show_win
;
; NMI_flag = 0;
;
L00DB:	lda     #$00
	sta     _NMI_flag
;
; while (1){   // infinite loop
;
	jmp     L00D7

.endproc

